### ISSUE TITLE
Hi, question about chain

### ISSUE THREAD

**Issue by dubiao** [dmgctrl/Promises-Swift#11]
I am new in Promise pattern.
I meet a problem that i have 3 tasks to call and each one depend on the previous' result.
I can do this by 

    let p1; 
    let p2; 
    let p3; 
    p1.then {
        p2.then {
            p3.then {
               hi, here is the result.
            }
        }
    }

But it bring me back to the callback-hell again.

Any advice? (except for RxSwift).

**Comment by dubiao** [comment]
Ha, I found this from the source:
    public func then<R>(block: (V) throws -> (R)) -> Promise<R>
It must be the solution.
Let me see...

**Comment by dubiao** [comment]
It not solve all my puzzles.
My p3 contains an async network op. And not possible to rewrite it. 
`Uploader.uploadFile(file: NSURL, block: (res) -> Void)`
Is there any idea like 
`p1.then(p2).then(p3)`
?

Or I should call like this

    p1.then ({....}) .then {
        Uploader.uploadFile()
    }
    // It's ugly.

**Comment by russellbstephens** [comment]
Hi, thanks for reaching out.  You should be able to chain these events together using a promise chain.  Examples can be found here: https://github.com/dmgctrl/Promises-Swift/blob/master/PromisesTests/PromisesTests.swift
